"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Krysta Gonzales and Zachary Brunell, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: kg36476
UT EID 2: ztb456
"""


def rail_fence_encode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: returns a single string that is encoded with
        rail fence algorithm
    """
    rail = []
    for _ in range(key):
        rail.append([''] * len(string))

    row, col = 0, 0
    direction = 1
    for char in string:
        rail[row][col] = char
        col += 1

        if row == key - 1:
            direction = -1
        elif row == 0:
            direction = 1

        row += direction

        if row >= key:
            row = key - 1
        elif row < 0:
            row = 0

    result = ''

    for row in rail:
        row_string = ''.join(row)
        result += row_string

    return result

def rail_fence_decode(string, key):
    """
    pre: string is a string of characters and key is a positive
        integer 2 or greater and strictly less than the length
        of string
    post: function returns a single string that is decoded with
        rail fence algorithm
    """
    rail = []
    for _ in range(key):
        rail.append([''] * len(string))

    row, col = 0, 0
    direction = 1

    for _ in string:
        rail[row][col] = '*'
        col += 1
        if row == key - 1:
            direction = -1
        elif row == 0:
            direction = 1
        row += direction

    index = 0
    for r in range(key):
        for c in range(len(string)):
            if rail[r][c] == '*':
                rail[r][c] = string[index]
                index += 1

    result = []
    row, col = 0, 0
    direction = 1
    for _ in string:
        result.append(rail[row][col])
        col += 1

        if row == key - 1:
            direction = -1
        elif row == 0:
            direction = 1
        row += direction

    return ''.join(result)


def filter_string(string):
    """
    pre: string is a string of characters
    post: function converts all characters to lower case and then
        removes all digits, punctuation marks, and spaces. It
        returns a single string with only lower case characters
    """
    result = ''
    for char in string:
        if char.isalpha():
            result += char.lower()
    return result

def encode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the plain text
    post: function returns a single character encoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    p_character = ord(p) - ord('a')
    s_character = ord(s) - ord('a')
    encoded_value = (p_character + s_character) % 26
    encoded_character = chr(encoded_value + ord('a'))
    return encoded_character

def decode_character(p, s):
    """
    pre: p is a character in the pass phrase and s is a character
        in the encrypted text
    post: function returns a single character decoded using the
        Vigenere algorithm. You may not use a 2-D list
    """
    p_character = ord(p) - ord('a')
    s_character = ord(s) - ord('a')

    decoded_character = (s_character - p_character + 26) % 26
    return chr(decoded_character + ord('a'))

def vigenere_encode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is encoded with
        Vigenere algorithm
    """
    string = string.lower()
    phrase = phrase.lower()
    filtered_string = filter_string(string)
    encoded_string = ""
    phrase_length = len(phrase)
    for i, char in enumerate(filtered_string):
        phrase_char = phrase[i % phrase_length]
        shift = ord(phrase_char) - ord('a')
        original_position = ord(char) - ord('a')
        new_position = (original_position + shift) % 26
        encoded_char = chr(new_position + ord('a'))
        encoded_string += encoded_char
    return encoded_string

def vigenere_decode(string, phrase):
    """
    pre: string is a string of characters and phrase is a pass phrase
    post: function returns a single string that is decoded with
        Vigenere algorithm
    """
    filtered_string = filter_string(string)
    decoded_string = ""
    phrase_length = len(phrase)

    for i, char in enumerate(filtered_string):
        phrase_char = phrase[i % phrase_length]
        shift = ord(phrase_char) - ord('a')
        encoded_position = ord(char) - ord('a')
        new_position = (encoded_position - shift + 26) % 26
        decoded_char = chr(new_position + ord('a'))
        decoded_string += decoded_char

    return decoded_string

def main():
    """Main function that reads stdin and runs each cipher"""
    print("Rail Fence Cipher\n")
    # read the plain text from stdin (terminal/input)
    plain_text_rail_fence = input("Plain Text: ")
    # read the key from stdin (terminal/input)
    key_rail_fence = int(input("Key: "))
    # encrypt and print the encoded text using rail fence cipher
    encoded_text_rail_fence = rail_fence_encode(plain_text_rail_fence, key_rail_fence)
    print(f"Encoded Text: {encoded_text_rail_fence}\n")
    # read encoded text from stdin (terminal/input)
    encoded_text_rail_fence_input = input("Encoded Text: ")
    # read the key from stdin (terminal/input)
    key_rail_fence_input = int(input("Key: "))
    # decrypt and print the plain text using rail fence cipher
    decoded_text_rail_fence = rail_fence_decode(encoded_text_rail_fence_input, key_rail_fence_input)
    print(f"Decoded Text: {decoded_text_rail_fence}\n")
    # read the plain text from stdin (terminal/input)
    print("Vigenere Cipher\n")
    plain_text_vigenere = input("Plain Text: ")
    # read the pass phrase from stdin (terminal/input)
    pass_phrase_vigenere = input("Pass Phrase: ")
    # encrypt and print the encoded text using Vigenere cipher
    encoded_text_vigenere = vigenere_encode(plain_text_vigenere, pass_phrase_vigenere)
    print(f"Encoded Text: {encoded_text_vigenere}\n")
    # read the encoded text from stdin (terminal/input)
    encoded_text_vigenere_input = input("Encoded Text: ")
    # read the pass phrase from stdin (terminal/input)
    pass_phrase_vigenere_input = input("Pass Phrase: ")
    # decrypt and print the plain text using Vigenere cipher
    decoded_text_vigenere = vigenere_decode(encoded_text_vigenere_input, pass_phrase_vigenere_input)
    print(f"Decoded Text: {decoded_text_vigenere}")
# Do NOT modify the following code.
if __name__ == "__main__":
    main()