"""
Student information for this assignment:
On my/our honor, Zachary Brunell, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: ztb456
"""
def group_sum(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to the
    given target.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if target == 0:
        return True
    if start >= len(nums):
        return False
    if group_sum(start + 1, nums, target):
        return True
    if group_sum(start + 1, nums, target - nums[start]):
        return True

    return False

def group_sum_6(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to the
    given target. Additionally, if there is are 6's present in the array, they must all
    be chosen.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if target == 0:
        return True
    if start >= len(nums):
        return False
    if nums[start] == 6:
        return group_sum_6(start + 1, nums, target - nums[start])
    if group_sum_6(start + 1, nums, target - nums[start]):
        return True
    if group_sum_6(start + 1, nums, target):
        return True
    return False

def group_no_adj(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if a value is chosen, the value immediately after
    (the value adjacent) cannot be chosen.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if target == 0:
        return True
    if start >= len(nums):
        return False
    if group_no_adj(start + 2, nums, target - nums[start]):
        return True
    if group_no_adj(start + 1, nums, target):
        return True
    return False

def group_sum_5(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if a multiple of 5 is in the array, it must be included
    If the value immediately following a multiple of 5 if 1, it must not be chosen

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if target == 0:
        return True
    if start >= len(nums):
        return False
    if nums[start] % 5 == 0:
        if start + 1 < len(nums) and nums[start + 1] == 1:
            return group_sum_5(start + 2, nums, target - nums[start])
        return group_sum_5(start + 1, nums, target - nums[start])
    return (group_sum_5(start + 1, nums, target - nums[start])
            or group_sum_5(start +1, nums, target))
def group_sum_clump(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if there is a group of identical numbers in succession,
    they must all be chosen, or none of them must be chosen.
    EX: [1, 2, 2, 2, 5, 2], all three of the middle 2's must be chosen, or none of them must be
    chosen to be included in the sum. One loop is allowed to check for identical numbers.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if target == 0:
        return True
    if start >= len(nums):
        return False
    n_start = nums[start]
    next_i = start + 1
    while next_i < len(nums) and nums[next_i] == nums[start]:
        n_start += nums[next_i]
        next_i += 1
    return (group_sum_clump(next_i, nums, target - n_start) or
            group_sum_clump(next_i, nums, target))

def split_array(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of these two groups must be equal
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    dic = {}
    def helper(start, target):
        if target == 0:
            return True
        if target < 0 or start >= len(nums):
            return False
        if (start, target) in dic:
            return dic[(start, target)]
        include = helper(start + 1, target - nums[start])
        exclude = helper(start + 1, target)
        result = include or exclude
        dic[(start, target)] = result
        return result
    total_sum = sum(nums)
    if not total_sum % 2 == 0:
        return False
    target = total_sum // 2
    return helper(0, target)

def split_odd_10(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of one group must be odd, while the other group must be a multiple of 10
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    def helper(start, odd, s10):
        if start == len(nums):
            return (odd % 2 != 0) and (s10 % 10 == 0)
        current = nums[start]
        including_odd = helper(start + 1 , odd + current, s10)
        including_s10 = helper(start + 1, odd, s10 + current)
        return including_odd or including_s10
    return helper(0, 0, 0)

def split_53(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of these two groups must be equal
    Additionally, all multiples of 5 must be in one group, and all multiples of 3 (and not 5)
    must be in the other group
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    def helper(start, s5, s3):
        if start == len(nums):
            return s5 == s3
        current = nums[start]
        if current % 5 == 0:
            return helper(start + 1, s5 + current, s3)
        if current % 3 ==0:
            return helper(start + 1, s5, s3 + current)
        return helper(start + 1, s5 + current, s3) or helper(start + 1, s5, s3 + current)
    return helper(0, 0, 0)
