
"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Zachary Brunell, this 
programming assignment is my own work and I have not provided this code to 
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: ztb456
"""
import sys
STEP_SIZE_CONSTANT = 3


def is_prime(n):
    """
    Determines if a number is prime.

    pre: n is a positive integer.
    post: Returns True if n is prime, otherwise returns False.
    """
    if n < 2:
        return False
    if n in (2, 3):
        return True
    if n % 2 == 0:
        return False
    for div in range(3, int(n ** 0.5) + 1, 2):
        if n % div == 0:
            return False
    return True


def next_prime(n):
    """Finds the next prime number greater than or equal to n.
    """
    while not is_prime(n):
        n += 1
    return n

def hash_word(s, size):
    """
    Hashes a lowercase string to an index in a hash table.

    pre: s is a lowercase string, and size is a positive integer representing either
         hash table size or the constant for double hashing.
    post: Returns an integer index in the range [0, size - 1] where the string hashes to.
    """
    hash_idx = 0
    for c in s:
        letter = ord(c) - 96  # Convert 'a' to 1, 'b' to 2, ..., 'z' to 26
        hash_idx = (hash_idx * 26 + letter) % size
    return hash_idx

def step_size(s):
    """
    Calculates step size for double hashing using STEP_SIZE_CONSTANT.

    pre: s is a lowercase string.
    post: Returns the calculated step size as an integer based on the provided string.
    """
    step = STEP_SIZE_CONSTANT - (hash_word(s, STEP_SIZE_CONSTANT) % STEP_SIZE_CONSTANT)
    return max(step, 1)  # Ensure step size is never 0

def insert_word(s, hash_table):
    """
    Inserts a string into the hash table using double hashing for collision resolution.
    No duplicates are allowed.

    pre: s is a string, and hash_table is a list representing the hash table.
    post: Inserts s into hash_table at the correct index; resolves any collisions
          by double hashing.
    """
    table_size = len(hash_table)
    index = hash_word(s, table_size)

    if hash_table[index] == "":
        hash_table[index] = s
        return

    step = step_size(s)
    original = index

    while hash_table[index] != "":
        if hash_table[index] == s:
            return
        index = (index + step) % table_size
        if index == original:
            return
    hash_table[index] = s

def find_word(s, hash_table):
    """
    Searches for a string in the hash table.
    Note: using the `in` operator is incorrect as that will be O(N). We want
          an O(1) time average time complexity using hashing.

    pre: s is a string, and hash_table is a list representing the hash table.
    post: Returns True if s is found in hash_table, otherwise returns False.
    """
    table_size = len(hash_table)
    index = hash_word(s, table_size)
    step = step_size(s)

    while hash_table[index] != "":
        if hash_table[index] == s:
            return True
        index = (index + step) % table_size
    return False

def is_reducible(s, hash_table, hash_memo):
    """
    Determines if a string is reducible using a recursive check.

    pre: s is a lowercase string, hash_table is a list representing the hash table,
         and hash_memo is a list representing the hash table
         for memoization.
    post: Returns True if s is reducible (also updates hash_memo by
          inserting s if reducible), otherwise returns False.
    """
    if s in ["a", "i", "o"]:
        return True
    if find_word(s, hash_memo):
        return True

    for i in range(len(s)):
        sub_word = s[:i] + s[i + 1:]
        if find_word(sub_word, hash_table) and is_reducible(sub_word, hash_table, hash_memo):
            insert_word(s, hash_memo)
            return True

    return False

def get_longest_words(string_list):
    """
    Finds longest words from a list.

    pre: string_list is a list of lowercase strings.
    post: Returns a list of words in string_list that have the maximum length.
    """
    if not string_list:
        return []
    max_length = max(len(word) for word in string_list)
    return [word for word in string_list if len(word) == max_length]

def main():
    """The main function that calculates the longest reducible words"""
    word_list = []
    try:
        for line in sys.stdin:
            word = line.strip()
            if word:
                word_list.append(word)
    except EOFError:
        pass

    word_list_length = len(word_list)
    if word_list_length == 0:
        return

    # Determine prime numbers for hash tables
    n_ = next_prime(2 * word_list_length)
    m_= next_prime(int(0.2 * word_list_length) + 1)

    # Create hash tables
    hash_list = [""] * n_
    hash_memo = [""] * m_

    # Insert words into hash table
    for word in word_list:
        insert_word(word, hash_list)

    # Find reducible words
    reducible_words = [word for word in word_list if is_reducible(word, hash_list, hash_memo)]

    # Get longest reducible words
    longest_reducible_words = get_longest_words(reducible_words)

    # Print longest reducible words in alphabetical order
    for word in sorted(longest_reducible_words):
        print(word)


if __name__ == "__main__":
    main()
